// Database (constants) file

// -- (global) database constants

// pagination value (skipping entries)
export const DB_PAGINATE = {
    notification: 20
}


// -- Cockroachdb (Prisma) configurations & constants

// user-id (uuid) length (generated by prisma)
export const UUID_LENGTH = 36


// -- Redis configurations & constants

// redis database indexes (0-15)
export enum REDIS_DB_INDEX {
    CACHE_LAYER, NOTIFICATIONS
}

// expiration date for redis:notifications (7 days = 604800 seconds)
export const REDIS_EXPIRE_NOTIFICATION_TIME = 604800

// generate redis:notification key
export const REDIS_KEYS = {
    // returns a valid (redis:notificaiton) key - <user_id:time>
    CreateNotificationKey: (user_id: string, date?: number) => `${user_id}:${date ?? new Date().getTime()}`,
}