### Signup
POST http://localhost:5000/v1/auth/signup
Content-Type: application/json

{
    "full_name": "Newton",
    "gender": "MALE",
    "email": "swuicnkds01@gmail.com",
    "password": "123456789",
    "username": "Artemixx",
    "bio": "I like 1, 2, 3 and 4",
    "interests": ["Psychology", "Astronomy", "Philosophy"],
    "prefered_langs": [
        "ENGLISH",
        "HEBREW"
    ]
}