### Signup
GET http://localhost:5000/v1/auth/
Aihtorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNGE0Y2QxNzUtZTJhMi00NGRjLTkyYWMtODNhNTZkMmUyNGNiIiwidXNlcm5hbWUiOiJTaGFkb3dDeWFuaWwxMDc3IiwiZW1haWwiOiJsaW9yYmVkb2sxMDc3QGdtYWlsLmNvbSIsImZ1bGxfbmFtZSI6Ikxpb3IgQmVkb2siLCJwYXNzd29yZCI6IiRhcmdvbjJpZCR2PTE5JG09NDA5Nix0PTMscD0xJGpiblZjbGRCenZ0c1R0YmR4eTEvN3ckZmNqYlRSSjcwR2pJNFQ1NHh0WEtQZG55dFBOaTFITVJHVERxNmd0cDhGRSIsImNyZWF0ZWRfYXQiOiIyMDIyLTA5LTIzVDE2OjI2OjMyLjA2OVoiLCJwcm9maWxlX3BpY19zcmMiOm51bGwsInBob25lX251bWJlciI6bnVsbCwiZ2VuZGVyIjoiTUFMRSIsImJpbyI6IkkgbGlrZSAxLCAyLCAzIGFuZCA0IiwiaW50ZXJlc3RzIjpbIlBzeWNob2xvZ3kiLCJBc3Ryb25vbXkiLCJQaGlsb3NvcGh5Il0sInByZWZlcmVkX2xhbmdzIjpbIkVOR0xJU0giLCJIRUJSRVciXSwibnVtX3N0YXJzIjowLCJzdGFyX2lkIjpudWxsLCJudW1fdmlld2VkX3Byb2ZpbGUiOjAsIm51bV9lZGl0ZWRfcHJvZmlsZSI6MjUsImlhdCI6MTY2Mzk1MDM5MiwiZXhwIjoxNjYzOTUxMjkyfQ.FxUS73BgXybEoktfDfL-oHRu2Ut3rumrpBYn8xupcPI